### PR TITLE
added missing fields from the submissions page

### PR DESCRIPTION
**Pull request by rla3rd**
I was just starting to play around with the raw rest api in a personal project when i came across this awesome project.  I am making the attempt to modernize the dead github openedgar project.  I plan on replacing all the broken api calls using your project, i'll send you updates if you don't mind as i find things missing.  i sent you a linkedin invite too, thanks.

### CODE REVIEW

**Review by dgunning — APPROVED** [review]
Seems okay. Will  do some testing especially on none-company Entities just in case some of those fields are Optional

**Comment by rla3rd** [comment]
could also convert all those dict calls to .get() then it wouldnt matter

**Comment by dgunning** [comment]
Accepted. Will perform additional tests. Thanks

**Comment by dgunning** [comment]
Ran batch tests on around 700 person entities and it seems fine as is.

Thanks

Dwight

**Comment by dgunning** [comment]
Released 2.8.3 with this PR.

Thanks

**Pull request merged**
